apiVersion: v1
kind: ServiceAccount
metadata:
  name: configmap-reader-sa
  labels:
    app: configmap-reader
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: configmap-reader-role
  labels:
    app: configmap-reader
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: configmap-reader-rb
  labels:
    app: configmap-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: configmap-reader-role
subjects:
  - kind: ServiceAccount
    name: configmap-reader-sa
